[devpdf]: Revise tests.
* font/devpdf/tests/check-default-foundry.sh.in: Test only the base 14
  fonts of the PDF standard unconditionally.  Test the remainder from
  the set of 35 commonly distributed only if a Ghostscript interpreter
  was detected at configuration time, because the latter fonts _must_ be
  embedded in PDF documents.  If they're not present, skip the test
  rather than failing it.
* font/devpdf/tests/check-urw-foundry.sh.in: Skip test if no URW fonts
  detected at configuration time, rather than failing it.
* m4/groff.m4 (GROFF_GROPDF_PROGRAM_NOTICE, GROFF_URW_FONTS_NOTICE):
  Drop warnings of expected test failures.  The tests no longer fail in
  the anticipated circumstances.

diff --git a/font/devpdf/tests/check-urw-foundry.sh.in b/font/devpdf/tests/check-urw-foundry.sh.in
--- a/font/devpdf/tests/check-urw-foundry.sh.in
+++ b/font/devpdf/tests/check-urw-foundry.sh.in
@@ -1,6 +1,6 @@
 #!/bin/sh
 #
-# Copyright (C) 2022 Free Software Foundation, Inc.
+# Copyright (C) 2022-2023 Free Software Foundation, Inc.
 #
 # This file is part of groff.
 #
@@ -19,8 +19,17 @@
 #
 
 # Ensure that groff's PDF device has URW font descriptions it expects.
+# These are generated at build time by afmtodit(1) if a URW font
+# directory was discovered at configuration time.
 
 devpdf_fontbuilddir="${abs_top_builddir:-.}"/font/devpdf
+urwfontsdir=@urwfontsdir@
+
+if [ -z "$urwfontsdir" ]
+then
+    echo "URW fonts not found at configuration time; skipping" >&2
+    exit 77 # skip
+fi
 
 fonts='AB
 ABI
@@ -67,7 +76,7 @@ do
     if ! test -f "$devpdf_fontbuilddir"/$f
     then
         echo test -f "$devpdf_fontbuilddir"/$f
-        echo FAILED >&2
+        echo ...FAILED >&2
         fail=yes
     fi
 done
